# Generated by Django 5.1.1 on 2024-09-21 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('give_back', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='bio',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='location',
            field=models.TextField(default=''),
        ),
    ]
