# Generated by Django 5.1.1 on 2024-09-21 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('give_back', '0002_alter_volunteer_bio_alter_volunteer_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='organization',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='organization',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='organization',
            name='website',
            field=models.URLField(default=''),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
