# Generated by Django 5.1.1 on 2024-09-21 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('give_back', '0003_alter_organization_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='description',
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
