# Generated by Django 5.1.1 on 2024-09-21 21:18

from django.db import migrations

def insert_static_data(apps, schema_editor):
    Service = apps.get_model('give_back', 'Service')
    Service.objects.create(name='Food')
    Service.objects.create(name='Shelter')
    Service.objects.create(name='Clothing')
    Service.objects.create(name='Education')
    Service.objects.create(name='Health')
    Service.objects.create(name='Transportation')
    Service.objects.create(name='Legal')
    Service.objects.create(name='Other')

class Migration(migrations.Migration):

    dependencies = [
        ('give_back', '0004_remove_service_description_alter_service_name'),
    ]

    operations = [
        migrations.RunPython(insert_static_data),
    ]
