# Generated by Django 5.1.1 on 2024-09-21 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('give_back', '0006_alter_organization_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
