# Generated by Django 5.1.1 on 2024-09-21 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('give_back', '0007_alter_organization_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='service_preferences',
            field=models.ManyToManyField(blank=True, null=True, to='give_back.service'),
        ),
    ]
