# Generated by Django 5.1.1 on 2024-09-21 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('give_back', '0009_alter_event_volunteers_alter_organization_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='volunteers',
            field=models.ManyToManyField(blank=True, to='give_back.volunteer'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='services',
            field=models.ManyToManyField(blank=True, to='give_back.service'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='give_back_user_set', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='give_back_user_permissions_set', to='auth.permission'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='service_preferences',
            field=models.ManyToManyField(blank=True, to='give_back.service'),
        ),
    ]
