# Generated by Django 5.1.1 on 2024-09-22 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('give_back', '0011_alter_event_organization_alter_event_service_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='time',
            new_name='end_time',
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.TimeField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='give_back.organization'),
            preserve_default=False,
        ),
    ]
