# Generated by Django 5.1.1 on 2024-09-22 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('give_back', '0012_rename_time_event_end_time_event_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='city',
            field=models.TextField(blank=True, null=True),
        ),
    ]
