# Generated by Django 5.1.1 on 2024-09-22 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('give_back', '0013_organization_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpactNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='give_back.client')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='give_back.event')),
            ],
        ),
    ]
